# Generated by Django 3.2.12 on 2022-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('EGP', 'EGP'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('to_currency', models.CharField(choices=[('EGP', 'EGP'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
